version: "3.9"
services:
  bback:
    image: bback
    build: bback/
    environment:
      - JAVA_REST_PORT=8091
    ports:
      - "8090:8090"
  bfront:
    image: bfront
    build: bfront/
    ports:
      - "8080:8080"
  bevaluator:
    image: bevaluator
    build: bevaluator/
    environment:
      - REST_PORT=8091
    ports:
      - "8091:8091"